# Generated by Django 5.2.15 on 2026-06-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='source_channel',
            field=models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('telegram', 'Telegram'), ('api', 'API')], default='api', max_length=20),
        ),
    ]
