# Generated by Django 5.2.15 on 2026-06-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_alter_customerrequest_source_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('classified', 'Classified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], db_index=True, default='queued', max_length=20),
        ),
    ]
